SELECT * INTO UGYFEL_MASKED2 FROM Ugyfel;
ALTER TABLE UGYFEL_MASKED2 ALTER COLUMN szul_ev INT;

ALTER TABLE UGYFEL_MASKED2
ALTER COLUMN login ADD MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",1)');  
ALTER TABLE UGYFEL_MASKED2
ALTER COLUMN email ADD MASKED WITH (FUNCTION = 'email()');  
ALTER TABLE UGYFEL_MASKED2
ALTER COLUMN szul_ev ADD MASKED WITH (FUNCTION = 'random(1980, 2020)');  
ALTER TABLE UGYFEL_MASKED2
ALTER COLUMN cim ADD MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",1)');  

CREATE USER MASKED_USER WITHOUT login;
Grant select on UGYFEL_MASKED2 to MASKED_USER

Execute as User='MASKED_USER';
SELECT * from UGYFEL_MASKED2